// <auto-generated />
using System;
using InfrastructureLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfrastructureLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250814155158_AddFavoritesTable")]
    partial class AddFavoritesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DomainLayer.Entities.BlogCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BlogCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#3B82F6",
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oyun incelemeleri ve değerlendirmeler",
                            Name = "İncelemeler",
                            Order = 1,
                            UpdatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Color = "#EF4444",
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oyun dünyasından son haberler",
                            Name = "Haberler",
                            Order = 2,
                            UpdatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Color = "#10B981",
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oyun rehberleri ve ipuçları",
                            Name = "Rehberler",
                            Order = 3,
                            UpdatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Color = "#8B5CF6",
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gaming teknolojileri ve donanım",
                            Name = "Teknoloji",
                            Order = 4,
                            UpdatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Color = "#F59E0B",
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "E-spor haberleri ve analizler",
                            Name = "E-Spor",
                            Order = 5,
                            UpdatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Color = "#6366F1",
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oyun endüstrisi analiz ve yorumlar",
                            Name = "Endüstri",
                            Order = 6,
                            UpdatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Color = "#84CC16",
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Eski oyunlar ve nostalji",
                            Name = "Retrospektif",
                            Order = 7,
                            UpdatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Color = "#06B6D4",
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kişisel oyun deneyimleri",
                            Name = "Kişisel Deneyim",
                            Order = 8,
                            UpdatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Color = "#EC4899",
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oyuncu toplulukları ve etkinlikler",
                            Name = "Topluluk",
                            Order = 9,
                            UpdatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Color = "#6B7280",
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Genel oyun konuları",
                            Name = "Diğer",
                            Order = 10,
                            UpdatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("GameId1")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GameId");

                    b.HasIndex("GameId1");

                    b.HasIndex("UserId");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("DomainLayer.Entities.BlogPostTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogPostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("BlogPostId", "TagId")
                        .IsUnique();

                    b.ToTable("BlogPostTags");
                });

            modelBuilder.Entity("DomainLayer.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BlogPostId")
                        .HasColumnType("int");

                    b.Property<int>("CommentableType")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DislikesCount")
                        .HasColumnType("int");

                    b.Property<int?>("ForumTopicId")
                        .HasColumnType("int");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("GuideId")
                        .HasColumnType("int");

                    b.Property<bool>("HasSpoiler")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LikesCount")
                        .HasColumnType("int");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int>("TargetEntityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId");

                    b.HasIndex("ForumTopicId");

                    b.HasIndex("GameId");

                    b.HasIndex("GuideId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.HasIndex("CommentableType", "TargetEntityId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("DomainLayer.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IGDBId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("DomainLayer.Entities.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FavoriteType")
                        .HasColumnType("int");

                    b.Property<int>("TargetEntityId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("DomainLayer.Entities.ForumCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ForumCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Genel oyun tartışmaları",
                            Name = "Genel Tartışma",
                            Order = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oyun yardımları ve teknik destek",
                            Name = "Yardım & Destek",
                            Order = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oyun inceleme ve değerlendirmeleri",
                            Name = "Oyun İncelemeleri",
                            Order = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oyun dünyasından haberler",
                            Name = "Haberler",
                            Order = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oyun rehberleri ve ipuçları",
                            Name = "Rehberler & İpuçları",
                            Order = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Multiplayer oyun tartışmaları",
                            Name = "Çok Oyunculu",
                            Order = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "E-spor ve turnuva tartışmaları",
                            Name = "E-Spor",
                            Order = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oyun indirim ve kampanyaları",
                            Name = "İndirimler",
                            Order = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oyun modları ve özelleştirmeler",
                            Name = "Mod & Özelleştirme",
                            Order = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "PC oyun donanımı ve optimizasyon",
                            Name = "PC Gaming",
                            Order = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Konsol oyun tartışmaları",
                            Name = "Konsol Gaming",
                            Order = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mobil oyun tartışmaları",
                            Name = "Mobile Gaming",
                            Order = 0
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Eski ve klasik oyunlar",
                            Name = "Retro Gaming",
                            Order = 0
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bağımsız oyun geliştiricileri",
                            Name = "Indie Oyunlar",
                            Order = 0
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diğer konular",
                            Name = "Diğer",
                            Order = 0
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.ForumTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ForumCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSticky")
                        .HasColumnType("bit");

                    b.Property<int>("ReplyCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ForumCategoryId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("ForumTopics");
                });

            modelBuilder.Entity("DomainLayer.Entities.ForumTopicTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ForumTopicId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("ForumTopicId", "TagId")
                        .IsUnique();

                    b.ToTable("ForumTopicTags");
                });

            modelBuilder.Entity("DomainLayer.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Developer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GameSeriesId")
                        .HasColumnType("int");

                    b.Property<int?>("IGDBId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IGDBLastSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IGDBLastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("IGDBSlug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IGDBUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDataComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEarlyAccess")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Storyline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameSeriesId");

                    b.HasIndex("IGDBId")
                        .IsUnique()
                        .HasFilter("[IGDBId] IS NOT NULL");

                    b.HasIndex("Name");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameBeatTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AllAvgSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("AllPolledCount")
                        .HasColumnType("int");

                    b.Property<int?>("CompletionistAvgSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("CompletionistPolledCount")
                        .HasColumnType("int");

                    b.Property<int?>("ExtraAvgSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("ExtraPolledCount")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("HltbGameId")
                        .HasColumnType("int");

                    b.Property<string>("HltbGameName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MainAvgSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("MainPolledCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.HasIndex("HltbGameId");

                    b.ToTable("GameBeatTimes");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeveloper")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublisher")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("GameId");

                    b.ToTable("GameCompanies");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameGameMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GameModeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameModeId");

                    b.HasIndex("GameId", "GameModeId")
                        .IsUnique();

                    b.ToTable("GameGameModes");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("GameId", "GenreId")
                        .IsUnique();

                    b.ToTable("GameGenres");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameIgdbRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CriticRating")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("CriticRatingCount")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IgdbLastSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("UserRating")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("UserRatingCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("GameIgdbRatings");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameKeyword", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("KeywordId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GameId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("GameKeywords");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<int?>("IGDBId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("MediaType")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "MediaType");

                    b.ToTable("GameMedia");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IGDBId")
                        .HasColumnType("int");

                    b.Property<string>("IGDBName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique()
                        .HasFilter("[IGDBId] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GameModes");
                });

            modelBuilder.Entity("DomainLayer.Entities.GamePlatform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.HasIndex("GameId", "PlatformId")
                        .IsUnique();

                    b.ToTable("GamePlatforms");
                });

            modelBuilder.Entity("DomainLayer.Entities.GamePlayerPerspective", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerPerspectiveId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GameId", "PlayerPerspectiveId");

                    b.HasIndex("PlayerPerspectiveId");

                    b.ToTable("GamePlayerPerspectives");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GameId", "UserId")
                        .IsUnique();

                    b.ToTable("GameRatings");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IGDBId")
                        .HasColumnType("int");

                    b.Property<string>("IGDBName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique()
                        .HasFilter("[IGDBId] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GameSeries");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("GameId", "TagId")
                        .IsUnique();

                    b.ToTable("GameTags");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("ThemeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ThemeId");

                    b.HasIndex("GameId", "ThemeId")
                        .IsUnique();

                    b.ToTable("GameThemes");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameWebsite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("IGDBId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("WebsiteType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "WebsiteType");

                    b.ToTable("GameWebsites");
                });

            modelBuilder.Entity("DomainLayer.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IGDBId")
                        .HasColumnType("int");

                    b.Property<string>("IGDBName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("DomainLayer.Entities.Guide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("GuideCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TableOfContents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("GameId");

                    b.HasIndex("GuideCategoryId");

                    b.HasIndex("IsFeatured");

                    b.HasIndex("IsPublished");

                    b.HasIndex("UserId");

                    b.ToTable("Guides");
                });

            modelBuilder.Entity("DomainLayer.Entities.GuideBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockType")
                        .HasColumnType("int");

                    b.Property<string>("Caption")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuideId")
                        .HasColumnType("int");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GuideId", "Order");

                    b.ToTable("GuideBlocks");
                });

            modelBuilder.Entity("DomainLayer.Entities.GuideCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IconClass")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Order");

                    b.ToTable("GuideCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yeni başlayanlar için temel rehberler",
                            IconClass = "fas fa-play-circle",
                            Name = "Başlangıç Rehberi",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ana ve yan görevler için detaylı rehberler",
                            IconClass = "fas fa-tasks",
                            Name = "Görev Rehberleri",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Zorlu boss mücadeleleri için stratejiler",
                            IconClass = "fas fa-dragon",
                            Name = "Boss Savaşları",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oyuncu karşı oyuncu mücadele rehberleri",
                            IconClass = "fas fa-sword",
                            Name = "PvP Rehberleri",
                            Order = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Karakter ve ekipman build rehberleri",
                            IconClass = "fas fa-tools",
                            Name = "Build Rehberleri",
                            Order = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Eşya, başarım ve koleksiyon rehberleri",
                            IconClass = "fas fa-trophy",
                            Name = "Koleksiyonlar",
                            Order = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hızlı tamamlama teknikleri",
                            IconClass = "fas fa-stopwatch",
                            Name = "Speedrun",
                            Order = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oyun modifikasyonları rehberleri",
                            IconClass = "fas fa-wrench",
                            Name = "Mod Rehberleri",
                            Order = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Performans ve ayar optimizasyonu",
                            IconClass = "fas fa-cog",
                            Name = "Optimizasyon",
                            Order = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oyun içi ekonomi ve ticaret rehberleri",
                            IconClass = "fas fa-coins",
                            Name = "Ekonomi",
                            Order = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Harita ve konum rehberleri",
                            IconClass = "fas fa-map",
                            Name = "Haritalar",
                            Order = 11
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Karakter seçimi ve gelişimi",
                            IconClass = "fas fa-user-friends",
                            Name = "Karakterler",
                            Order = 12
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gizli içerikler ve easter egg'ler",
                            IconClass = "fas fa-eye",
                            Name = "Sırlar",
                            Order = 13
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Genel oyun ipuçları ve taktikler",
                            IconClass = "fas fa-lightbulb",
                            Name = "İpuçları",
                            Order = 14
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diğer rehber türleri",
                            IconClass = "fas fa-ellipsis-h",
                            Name = "Diğer",
                            Order = 99
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.GuideTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuideId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("GuideId", "TagId")
                        .IsUnique();

                    b.ToTable("GuideTags");
                });

            modelBuilder.Entity("DomainLayer.Entities.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IGDBId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("DomainLayer.Entities.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BlogPostId")
                        .HasColumnType("int");

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ForumTopicId")
                        .HasColumnType("int");

                    b.Property<int?>("GuideId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<int>("LikableType")
                        .HasColumnType("int");

                    b.Property<int>("TargetEntityId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId");

                    b.HasIndex("CommentId");

                    b.HasIndex("ForumTopicId");

                    b.HasIndex("GuideId");

                    b.HasIndex("UserId", "LikableType", "TargetEntityId")
                        .IsUnique();

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("DomainLayer.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("int");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TriggeredByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TriggeredByUserId");

                    b.HasIndex("UserId", "CreatedDate");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DomainLayer.Entities.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IGDBId")
                        .HasColumnType("int");

                    b.Property<string>("IGDBName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique()
                        .HasFilter("[IGDBId] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("DomainLayer.Entities.PlayerPerspective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IGDBId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PlayerPerspectives");
                });

            modelBuilder.Entity("DomainLayer.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JwtId")
                        .IsUnique();

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("DomainLayer.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evidence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReportType")
                        .HasColumnType("int");

                    b.Property<int>("ReportableEntityId")
                        .HasColumnType("int");

                    b.Property<int>("ReportableType")
                        .HasColumnType("int");

                    b.Property<int>("ReporterId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("ReportableType", "ReportableEntityId");

                    b.HasIndex("ReporterId", "ReportableType", "ReportableEntityId")
                        .IsUnique();

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("DomainLayer.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IGDBId")
                        .HasColumnType("int");

                    b.Property<string>("IGDBName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DomainLayer.Entities.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IGDBId")
                        .HasColumnType("int");

                    b.Property<string>("IGDBName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique()
                        .HasFilter("[IGDBId] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("DomainLayer.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("XP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DomainLayer.Entities.UserGameStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique();

                    b.ToTable("UserGameStatuses");
                });

            modelBuilder.Entity("DomainLayer.Entities.BlogPost", b =>
                {
                    b.HasOne("DomainLayer.Entities.BlogCategory", "Category")
                        .WithMany("BlogPosts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DomainLayer.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DomainLayer.Entities.Game", null)
                        .WithMany("BlogPosts")
                        .HasForeignKey("GameId1");

                    b.HasOne("DomainLayer.Entities.User", "User")
                        .WithMany("BlogPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Entities.BlogPostTag", b =>
                {
                    b.HasOne("DomainLayer.Entities.BlogPost", "BlogPost")
                        .WithMany("BlogPostTags")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Tag", "Tag")
                        .WithMany("BlogPostTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DomainLayer.Entities.Comment", b =>
                {
                    b.HasOne("DomainLayer.Entities.BlogPost", null)
                        .WithMany("Comments")
                        .HasForeignKey("BlogPostId");

                    b.HasOne("DomainLayer.Entities.ForumTopic", null)
                        .WithMany("Comments")
                        .HasForeignKey("ForumTopicId");

                    b.HasOne("DomainLayer.Entities.Game", null)
                        .WithMany("Comments")
                        .HasForeignKey("GameId");

                    b.HasOne("DomainLayer.Entities.Guide", null)
                        .WithMany("Comments")
                        .HasForeignKey("GuideId");

                    b.HasOne("DomainLayer.Entities.Comment", "ParentComment")
                        .WithMany("ChildComments")
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("DomainLayer.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Entities.Favorite", b =>
                {
                    b.HasOne("DomainLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Entities.ForumTopic", b =>
                {
                    b.HasOne("DomainLayer.Entities.ForumCategory", "ForumCategory")
                        .WithMany("ForumTopics")
                        .HasForeignKey("ForumCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DomainLayer.Entities.User", "User")
                        .WithMany("ForumTopics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForumCategory");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Entities.ForumTopicTag", b =>
                {
                    b.HasOne("DomainLayer.Entities.ForumTopic", "ForumTopic")
                        .WithMany("ForumTopicTags")
                        .HasForeignKey("ForumTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Tag", "Tag")
                        .WithMany("ForumTopicTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForumTopic");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DomainLayer.Entities.Game", b =>
                {
                    b.HasOne("DomainLayer.Entities.GameSeries", "GameSeries")
                        .WithMany("Games")
                        .HasForeignKey("GameSeriesId");

                    b.Navigation("GameSeries");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameBeatTime", b =>
                {
                    b.HasOne("DomainLayer.Entities.Game", "Game")
                        .WithOne("GameBeatTime")
                        .HasForeignKey("DomainLayer.Entities.GameBeatTime", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameCompany", b =>
                {
                    b.HasOne("DomainLayer.Entities.Company", "Company")
                        .WithMany("GameCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Game", "Game")
                        .WithMany("GameCompanies")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameGameMode", b =>
                {
                    b.HasOne("DomainLayer.Entities.Game", "Game")
                        .WithMany("GameGameModes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.GameMode", "GameMode")
                        .WithMany("GameGameModes")
                        .HasForeignKey("GameModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GameMode");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameGenre", b =>
                {
                    b.HasOne("DomainLayer.Entities.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameIgdbRating", b =>
                {
                    b.HasOne("DomainLayer.Entities.Game", "Game")
                        .WithOne("GameIgdbRating")
                        .HasForeignKey("DomainLayer.Entities.GameIgdbRating", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameKeyword", b =>
                {
                    b.HasOne("DomainLayer.Entities.Game", "Game")
                        .WithMany("GameKeywords")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Keyword", "Keyword")
                        .WithMany("GameKeywords")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Keyword");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameMedia", b =>
                {
                    b.HasOne("DomainLayer.Entities.Game", "Game")
                        .WithMany("GameMedia")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DomainLayer.Entities.GamePlatform", b =>
                {
                    b.HasOne("DomainLayer.Entities.Game", "Game")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Platform", "Platform")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("DomainLayer.Entities.GamePlayerPerspective", b =>
                {
                    b.HasOne("DomainLayer.Entities.Game", "Game")
                        .WithMany("GamePlayerPerspectives")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.PlayerPerspective", "PlayerPerspective")
                        .WithMany("GamePlayerPerspectives")
                        .HasForeignKey("PlayerPerspectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("PlayerPerspective");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameRating", b =>
                {
                    b.HasOne("DomainLayer.Entities.Game", "Game")
                        .WithMany("GameRatings")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameTag", b =>
                {
                    b.HasOne("DomainLayer.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Tag", "Tag")
                        .WithMany("GameTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameTheme", b =>
                {
                    b.HasOne("DomainLayer.Entities.Game", "Game")
                        .WithMany("GameThemes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Theme", "Theme")
                        .WithMany("GameThemes")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameWebsite", b =>
                {
                    b.HasOne("DomainLayer.Entities.Game", "Game")
                        .WithMany("GameWebsites")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DomainLayer.Entities.Guide", b =>
                {
                    b.HasOne("DomainLayer.Entities.Game", "Game")
                        .WithMany("Guides")
                        .HasForeignKey("GameId");

                    b.HasOne("DomainLayer.Entities.GuideCategory", "GuideCategory")
                        .WithMany("Guides")
                        .HasForeignKey("GuideCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DomainLayer.Entities.User", "User")
                        .WithMany("Guides")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GuideCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Entities.GuideBlock", b =>
                {
                    b.HasOne("DomainLayer.Entities.Guide", "Guide")
                        .WithMany("GuideBlocks")
                        .HasForeignKey("GuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guide");
                });

            modelBuilder.Entity("DomainLayer.Entities.GuideTag", b =>
                {
                    b.HasOne("DomainLayer.Entities.Guide", "Guide")
                        .WithMany("GuideTags")
                        .HasForeignKey("GuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Tag", "Tag")
                        .WithMany("GuideTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guide");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DomainLayer.Entities.Like", b =>
                {
                    b.HasOne("DomainLayer.Entities.BlogPost", null)
                        .WithMany("Likes")
                        .HasForeignKey("BlogPostId");

                    b.HasOne("DomainLayer.Entities.Comment", null)
                        .WithMany("Likes")
                        .HasForeignKey("CommentId");

                    b.HasOne("DomainLayer.Entities.ForumTopic", null)
                        .WithMany("Likes")
                        .HasForeignKey("ForumTopicId");

                    b.HasOne("DomainLayer.Entities.Guide", null)
                        .WithMany("Likes")
                        .HasForeignKey("GuideId");

                    b.HasOne("DomainLayer.Entities.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Entities.Notification", b =>
                {
                    b.HasOne("DomainLayer.Entities.User", "TriggeredByUser")
                        .WithMany("TriggeredNotifications")
                        .HasForeignKey("TriggeredByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DomainLayer.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TriggeredByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Entities.RefreshToken", b =>
                {
                    b.HasOne("DomainLayer.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Entities.Report", b =>
                {
                    b.HasOne("DomainLayer.Entities.User", "Reporter")
                        .WithMany("Reports")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.User", "ReviewedByUser")
                        .WithMany("ReviewedReports")
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Reporter");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("DomainLayer.Entities.UserGameStatus", b =>
                {
                    b.HasOne("DomainLayer.Entities.Game", "Game")
                        .WithMany("UserGameStatuses")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.User", "User")
                        .WithMany("UserGameStatuses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Entities.BlogCategory", b =>
                {
                    b.Navigation("BlogPosts");
                });

            modelBuilder.Entity("DomainLayer.Entities.BlogPost", b =>
                {
                    b.Navigation("BlogPostTags");

                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("DomainLayer.Entities.Comment", b =>
                {
                    b.Navigation("ChildComments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("DomainLayer.Entities.Company", b =>
                {
                    b.Navigation("GameCompanies");
                });

            modelBuilder.Entity("DomainLayer.Entities.ForumCategory", b =>
                {
                    b.Navigation("ForumTopics");
                });

            modelBuilder.Entity("DomainLayer.Entities.ForumTopic", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ForumTopicTags");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("DomainLayer.Entities.Game", b =>
                {
                    b.Navigation("BlogPosts");

                    b.Navigation("Comments");

                    b.Navigation("GameBeatTime");

                    b.Navigation("GameCompanies");

                    b.Navigation("GameGameModes");

                    b.Navigation("GameGenres");

                    b.Navigation("GameIgdbRating");

                    b.Navigation("GameKeywords");

                    b.Navigation("GameMedia");

                    b.Navigation("GamePlatforms");

                    b.Navigation("GamePlayerPerspectives");

                    b.Navigation("GameRatings");

                    b.Navigation("GameThemes");

                    b.Navigation("GameWebsites");

                    b.Navigation("Guides");

                    b.Navigation("UserGameStatuses");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameMode", b =>
                {
                    b.Navigation("GameGameModes");
                });

            modelBuilder.Entity("DomainLayer.Entities.GameSeries", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("DomainLayer.Entities.Genre", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("DomainLayer.Entities.Guide", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("GuideBlocks");

                    b.Navigation("GuideTags");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("DomainLayer.Entities.GuideCategory", b =>
                {
                    b.Navigation("Guides");
                });

            modelBuilder.Entity("DomainLayer.Entities.Keyword", b =>
                {
                    b.Navigation("GameKeywords");
                });

            modelBuilder.Entity("DomainLayer.Entities.Platform", b =>
                {
                    b.Navigation("GamePlatforms");
                });

            modelBuilder.Entity("DomainLayer.Entities.PlayerPerspective", b =>
                {
                    b.Navigation("GamePlayerPerspectives");
                });

            modelBuilder.Entity("DomainLayer.Entities.Tag", b =>
                {
                    b.Navigation("BlogPostTags");

                    b.Navigation("ForumTopicTags");

                    b.Navigation("GameTags");

                    b.Navigation("GuideTags");
                });

            modelBuilder.Entity("DomainLayer.Entities.Theme", b =>
                {
                    b.Navigation("GameThemes");
                });

            modelBuilder.Entity("DomainLayer.Entities.User", b =>
                {
                    b.Navigation("BlogPosts");

                    b.Navigation("Comments");

                    b.Navigation("ForumTopics");

                    b.Navigation("Guides");

                    b.Navigation("Likes");

                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reports");

                    b.Navigation("ReviewedReports");

                    b.Navigation("TriggeredNotifications");

                    b.Navigation("UserGameStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
